"""create news tables

Revision ID: cbd15ef96636
Revises: c4e2f8b1a3d5
Create Date: 2026-04-17 18:54:47.291823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbd15ef96636'
down_revision: Union[str, None] = 'c4e2f8b1a3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('rss_url', sa.String(length=500), nullable=False),
    sa.Column('credibility_weight', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rss_url')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('commodities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('regions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('direction_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('horizon', sa.String(length=20), nullable=True),
    sa.Column('trader_impact', sa.Text(), nullable=True),
    sa.Column('broker_impact', sa.Text(), nullable=True),
    sa.Column('exporter_impact', sa.Text(), nullable=True),
    sa.Column('story_id', sa.String(length=64), nullable=True),
    sa.Column('is_classified', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_news_articles_archived', 'news_articles', ['is_archived'], unique=False)
    op.create_index('ix_news_articles_cluster_id', 'news_articles', ['cluster_id'], unique=False)
    op.create_index('ix_news_articles_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('ix_news_articles_story_id', 'news_articles', ['story_id'], unique=False)
    op.create_table('user_cluster_taste',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('taste_weight', sa.Float(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('avg_dwell_time', sa.Float(), nullable=False),
    sa.Column('is_seeded', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cluster_id', name='uq_user_cluster_taste')
    )
    op.create_table('news_engagement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.String(length=100), nullable=True),
    sa.Column('dwell_time_s', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_engagement_article_id', 'news_engagement', ['article_id'], unique=False)
    op.create_index('ix_news_engagement_created_at', 'news_engagement', ['created_at'], unique=False)
    op.create_index('ix_news_engagement_user_id', 'news_engagement', ['user_id'], unique=False)
    op.create_table('news_trending',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.String(length=100), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('velocity_score', sa.Float(), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'article_id', name='uq_trending_segment_article')
    )
    op.create_index('ix_news_trending_segment_id', 'news_trending', ['segment_id'], unique=False)
    op.drop_constraint(op.f('group_activity_cache_group_id_fkey'), 'group_activity_cache', type_='foreignkey')
    op.create_foreign_key(None, 'group_activity_cache', 'groups', ['group_id'], ['id'])
    op.drop_constraint(op.f('group_embeddings_group_id_fkey'), 'group_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'group_embeddings', 'groups', ['group_id'], ['id'])
    op.drop_index(op.f('idx_group_members_user'), table_name='group_members')
    op.drop_constraint(op.f('group_members_group_id_fkey'), 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'])
    op.drop_constraint(op.f('user_embeddings_user_id_fkey'), 'user_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'user_embeddings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('user_embeddings_user_id_fkey'), 'user_embeddings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(op.f('group_members_group_id_fkey'), 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_group_members_user'), 'group_members', ['user_id'], unique=False)
    op.drop_constraint(None, 'group_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('group_embeddings_group_id_fkey'), 'group_embeddings', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'group_activity_cache', type_='foreignkey')
    op.create_foreign_key(op.f('group_activity_cache_group_id_fkey'), 'group_activity_cache', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_news_trending_segment_id', table_name='news_trending')
    op.drop_table('news_trending')
    op.drop_index('ix_news_engagement_user_id', table_name='news_engagement')
    op.drop_index('ix_news_engagement_created_at', table_name='news_engagement')
    op.drop_index('ix_news_engagement_article_id', table_name='news_engagement')
    op.drop_table('news_engagement')
    op.drop_table('user_cluster_taste')
    op.drop_index('ix_news_articles_story_id', table_name='news_articles')
    op.drop_index('ix_news_articles_published_at', table_name='news_articles')
    op.drop_index('ix_news_articles_cluster_id', table_name='news_articles')
    op.drop_index('ix_news_articles_archived', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_table('news_sources')
    # ### end Alembic commands ###
